<template>
  <div class="page">
    <div class="hero"><div><div class="eyebrow">WORKSPACE / TASKS</div><h2>任务管理</h2><p>集中创建、监控和管理问卷自动化任务</p></div><el-button class="create-btn" type="primary" size="large" @click="dialog=true">＋ 创建新任务</el-button></div>
    <div class="stats"><div class="stat"><span>全部任务</span><strong>{{store.tasks.length}}</strong></div><div class="stat blue"><span>进行中</span><strong>{{activeCount}}</strong></div><div class="stat green"><span>已完成</span><strong>{{doneCount}}</strong></div><div class="stat orange"><span>成功提交</span><strong>{{successCount}}</strong></div></div>
    <div class="card table-card"><el-empty v-if="!store.tasks.length" description="还没有任务"/><el-table v-else :data="store.tasks" stripe><el-table-column prop="task_id" label="任务 ID" min-width="220"/><el-table-column prop="url" label="问卷 URL" show-overflow-tooltip/><el-table-column label="代理地区" width="120"><template #default="{row}"><el-tag v-if="row.proxy?.enabled" type="info">{{row.proxy.area}}</el-tag><span v-else>直连</span></template></el-table-column><el-table-column label="进度" width="200"><template #default="{row}"><el-progress :percentage="row.progress"/></template></el-table-column><el-table-column label="状态" width="110"><template #default="{row}"><el-tag>{{statusText(row.status)}}</el-tag></template></el-table-column><el-table-column label="操作" width="150"><template #default="{row}"><el-button link type="primary" @click="router.push('/tasks/'+row.task_id)">查看</el-button><el-button link type="danger" @click="remove(row.task_id)">删除</el-button></template></el-table-column></el-table></div>

    <el-dialog v-model="dialog" title="创建新任务" width="720px" destroy-on-close>
      <el-steps :active="step" finish-status="success" simple><el-step title="输入 URL"/><el-step title="预览问卷"/><el-step title="配置提交"/></el-steps>
      <el-form v-if="step===0" class="wizard-form" :model="form"><el-form-item label="问卷 URL"><el-input v-model="form.url"/></el-form-item><el-checkbox v-model="form.use_ai" :disabled="!ai.available">使用 AI 识别反向题</el-checkbox><br/><el-button type="primary" :loading="loading" @click="analyze">解析问卷</el-button></el-form>
      <div v-else-if="step===1"><el-alert title="问卷解析成功" type="success" show-icon/><p>共 {{questionnaire?.total_questions}} 道题</p><QuestionPreview v-if="questionnaire" :questions="questionnaire.questions"/><el-button @click="step=0">上一步</el-button><el-button type="primary" @click="step=2">下一步</el-button></div>
      <el-form v-else class="wizard-form" :model="form"><el-form-item label="提交数量"><el-input-number v-model="form.count" :min="1" :max="1000"/></el-form-item><el-form-item label="模式"><el-radio-group v-model="form.mode"><el-radio value="random">随机</el-radio><el-radio value="high_reliability">高可靠性</el-radio></el-radio-group></el-form-item><el-form-item v-if="form.mode==='high_reliability'" label="态度"><el-radio-group v-model="form.attitude"><el-radio value="positive">积极</el-radio><el-radio value="negative">消极</el-radio></el-radio-group></el-form-item><ProxyConfigForm v-model="form.proxy"/><el-form-item label="浏览器调试"><el-switch v-model="form.debug"/></el-form-item><el-button @click="step=1">上一步</el-button><el-button type="primary" :loading="loading" @click="create">创建并开始任务</el-button></el-form>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import {computed,onMounted,reactive,ref,watch} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {useRouter} from 'vue-router'
import {useTaskStore} from '@/stores/task'; import {useAiStore} from '@/stores/ai'; import {analyzeQuestionnaire} from '@/api/questionnaire'
import type {ProxyConfig,Questionnaire} from '@/types'
import QuestionPreview from '@/components/Questionnaire/QuestionPreview.vue'; import ProxyConfigForm from '@/components/Task/ProxyConfigForm.vue'
const defaultProxy=():ProxyConfig=>({enabled:false,provider:'kuaidaili',area:'',carrier:0,rotate_per_submission:true,dedup:true,verify_exit:true,location_match:'relaxed',required:true,max_acquire_attempts:3})
const store=useTaskStore(),ai=useAiStore(),router=useRouter();const dialog=ref(false),step=ref(0),loading=ref(false),questionnaire=ref<Questionnaire>()
const form=reactive({url:'',count:10,mode:'random' as 'random'|'high_reliability',attitude:'positive' as 'positive'|'negative',use_ai:localStorage.getItem('questionnaire_use_ai')==='true',add_variation:false,variation_ratio:15,debug:false,proxy:defaultProxy()})
watch(()=>form.use_ai,v=>localStorage.setItem('questionnaire_use_ai',String(v)));onMounted(()=>{store.fetchList();ai.fetchConfig()})
const activeCount=computed(()=>store.tasks.filter(t=>t.status==='processing'||t.status==='pending').length),doneCount=computed(()=>store.tasks.filter(t=>t.status==='completed').length),successCount=computed(()=>store.tasks.reduce((n,t)=>n+t.submitted,0));const statusText=(s:string)=>({pending:'等待中',processing:'进行中',completed:'已完成',failed:'失败',cancelled:'已停止'}[s]||s)
const remove=async(id:string)=>{try{await ElMessageBox.confirm('确定删除该任务吗？','确认');await store.remove(id);ElMessage.success('已删除')}catch{}}
const analyze=async()=>{if(!form.url)return ElMessage.warning('请输入问卷 URL');loading.value=true;try{questionnaire.value=(await analyzeQuestionnaire(form.url,form.use_ai)).data.data;step.value=1}catch(error:any){ElMessage.error(error.response?.data?.detail||'解析失败')}finally{loading.value=false}}
const create=async()=>{if(!questionnaire.value)return ElMessage.error('请先解析问卷');if(form.proxy.enabled&&!form.proxy.area.trim())return ElMessage.warning('请输入代理目标地区');loading.value=true;try{const task=await store.create({task_id:questionnaire.value.task_id,url:form.url,count:form.count,mode:form.mode,proxy:form.proxy.enabled?form.proxy:undefined,config:form.mode==='high_reliability'?{attitude:form.attitude,add_variation:form.add_variation,variation_ratio:form.variation_ratio/100,debug:form.debug}:{attitude:'positive',add_variation:false,variation_ratio:0.05,debug:form.debug}});dialog.value=false;step.value=0;await router.push('/tasks/'+task.task_id)}catch(error:any){ElMessage.error(error.response?.data?.detail||'创建任务失败')}finally{loading.value=false}}
</script>
<style scoped>.hero{display:flex;justify-content:space-between;align-items:center;padding:28px 30px;border-radius:16px;background:linear-gradient(110deg,#1d3263,#4263b8);color:#fff}.eyebrow{font-size:11px;letter-spacing:2px;opacity:.65}.hero h2{margin:7px 0}.hero p{margin:0}.create-btn{background:#fff;color:#3454bd}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:20px 0}.stat{padding:18px 20px;border-radius:12px;background:#fff;border-left:4px solid #7c8ca8}.stat span{display:block;color:#8b98aa}.stat strong{display:block;font-size:25px;margin-top:8px}.blue{border-color:#5d7df2}.green{border-color:#35b98a}.orange{border-color:#f3a43b}.table-card{padding:10px 18px}.wizard-form{padding:28px 20px}.el-steps{margin:15px 0 25px}</style>
