export interface User { id:number|string; username:string; email?:string }
export type SubmitMode='random'|'high_reliability'|'proportional'
export interface Question { id:string; type:string; label:string; options:any[]; required:boolean; is_scale:boolean; is_reverse:boolean; reverse_confidence:number|null; detection_method?:'ai'|'keyword'|'structure'; positive_values?:any[]; negative_values?:any[]; neutral_values?:any[]; ratio_eligible?:boolean; ratio_kind?:'single'|'multiple'; selection_min?:number|null; selection_max?:number|null; parent_question_id?:string|null; ratio_display_key?:string|null; display_order?:number; ratio_zero_values?:any[] }
export interface Questionnaire { task_id:string; activity_id:string; url:string; total_questions:number; question_types:Record<string,number>; questions:Question[]; scale_questions:number; reverse_items:string[]; detection_method?:'ai'|'keyword'|'structure' }
export interface SubmitConfig { attitude:'positive'|'negative'; add_variation:boolean; variation_ratio:number; debug:boolean; max_submit_attempts?:number }
export interface AITextAnswerConfig { enabled:boolean; batch_size:number; max_generation_attempts:number }
export interface ProportionOptionConfig { value:any; percentage:number }
export interface ProportionQuestionConfig { question_id:string; enabled:boolean; options:ProportionOptionConfig[] }
export interface ProportionConfig { questions:ProportionQuestionConfig[]; seed:number; max_submit_attempts:number }
export interface ProxyConfig { enabled:boolean; provider:'kuaidaili'; area:string; carrier:0|1|2|3; rotate_per_submission:boolean; dedup:boolean; verify_exit:boolean; location_match:'strict'|'relaxed'; required:boolean; max_acquire_attempts:number }
export interface ProxyResult { proxy_endpoint?:string; proxy_requested_area?:string; proxy_reported_location?:string; proxy_exit_ip?:string; proxy_carrier?:string; proxy_remaining_seconds?:number; proxy_latency_ms?:number; proxy_attempts?:number; failure_stage?:string }
export interface Task { task_id:string; status:'pending'|'processing'|'completed'|'failed'|'cancelled'; submitted:number; failed:number; total:number; progress:number; start_time:string; end_time?:string|null; results?:Array<{index:number;status:'success'|'failed';error?:string}&ProxyResult>; url?:string; title?:string; mode?:SubmitMode; proxy?:ProxyConfig; ai_text_enabled?:boolean; ai_text_status?:string; ai_text_generated_count?:number; ai_text_error?:string|null; proportion_plan_status?:string; proportion_plan_count?:number }
